# Generated by Django 5.2.5 on 2025-08-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['supervisor', 'asm']}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='teamlead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teamlead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='asm',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'asm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='avp',
            field=models.ForeignKey(limit_choices_to={'role__in': ['avp', 'vp', 'gm', 'president']}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.group'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
