# Generated by Django 5.2.5 on 2025-08-28 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['team__name', 'group_type', 'name']},
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('regular', 'Regular Sales Group'), ('tsg', 'Technical Sales Group')], default='regular', help_text='Regular groups have supervisors, TSG groups are managed directly by AVPs', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Required for regular groups, not used for TSG groups', limit_choices_to={'role__in': ['supervisor', 'asm']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
