# Generated by Django 5.2.5 on 2026-01-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_group_options_group_group_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='quota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales quota for this user in this group (Profit based)', max_digits=12),
        ),
    ]
