# Generated by Django 6.0.1 on 2026-01-17 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_supervisorcommitmentlog_personalcontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsmPersonalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asm', models.ForeignKey(limit_choices_to={'role': 'asm'}, on_delete=django.db.models.deletion.CASCADE, related_name='asm_team_targets', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asm_targets', to='teams.team')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('team', 'asm', 'month')},
            },
        ),
    ]
