# Generated by Django 6.0.1 on 2026-02-04 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_rolemonthlyquota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemonthlyquota',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['supervisor', 'asm', 'avp', 'gm', 'vp']}, on_delete=django.db.models.deletion.CASCADE, related_name='role_monthly_quotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
