# Generated by Django 6.0.1 on 2026-02-05 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_companyannualtarget_companyannualtargetlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tech_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['techmgr', 'asst_techmgr']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsg_managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('regular', 'Regular Sales Group'), ('tsg', 'Technical Sales Group')], default='regular', help_text='Regular groups have supervisors; TSG groups are managed by the Technical Manager/Assistant Technical Manager', max_length=20),
        ),
    ]
