# Generated by Django 6.0.1 on 2026-02-05 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_tech_manager_alter_group_group_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avp',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['avp', 'vp', 'gm', 'president']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
