# Generated by Django 5.2.5 on 2026-08-06 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_team_avp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='sm_managers',
            field=models.ManyToManyField(blank=True, help_text='Sales Managers responsible for this group. One SM can manage multiple groups across a team.', limit_choices_to={'role': 'sm'}, related_name='sm_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
