# Generated by Django 5.2.5 on 2026-09-04 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_group_requires_sm_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sm_managers',
            field=models.ManyToManyField(blank=True, help_text='Sales Managers (SM/ASM) responsible for this group. One manager can oversee multiple groups within a team.', limit_choices_to={'role__in': ['sm', 'asm']}, related_name='sm_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
