# Generated by Django 5.2.5 on 2025-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, help_text='3-letter initials for the user (e.g., JDO for John Doe)', max_length=3),
        ),
    ]
