# Generated by Django 6.0.1 on 2026-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('avp', 'AVP'), ('supervisor', 'Supervisor'), ('salesperson', 'Salesperson'), ('vp', 'Vice President'), ('gm', 'General Manager'), ('president', 'President'), ('asm', 'ASM'), ('sm', 'Sales Manager'), ('teamlead', 'Teamlead'), ('techmgr', 'Technical Manager'), ('asst_techmgr', 'Assistant Technical Manager')], default='salesperson', max_length=20),
        ),
    ]
