# Generated by Django 5.2.5 on 2026-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_activity_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the user', null=True, upload_to='profile_pictures/'),
        ),
    ]
