# Generated by Django 5.2.5 on 2026-03-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Digital signature image for proposals', null=True, upload_to='signatures/'),
        ),
    ]
