# Generated by Django 5.2.5 on 2026-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('account_manager', 'Account Manager'), ('sales_supervisor', 'Sales Supervisor'), ('president', 'President'), ('vice_president', 'Vice President'), ('general_manager', 'General Manager'), ('assistant_vp', 'Assistant VP'), ('sales_manager', 'Sales Manager'), ('accounting_manager', 'Accounting Manager'), ('operation_manager', 'Operation Manager'), ('cto', 'CTO'), ('ceo', 'CEO'), ('chairman', 'Chairman'), ('warehouse_supervisor', 'Warehouse Supervisor'), ('purchasing_supervisor', 'Purchasing Supervisor'), ('technical_manager', 'Technical Manager'), ('assistant_technical_manager', 'Assistant Technical Manager'), ('sr_teamlead', 'Sr. Teamlead'), ('purchasing_staff', 'Purchasing Staff'), ('accounting_staff', 'Accounting Staff'), ('warehouse_staff', 'Warehouse Staff'), ('hr_officer', 'HR Officer')], max_length=50),
        ),
    ]
