# Generated by Django 5.2.5 on 2026-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('avp', 'AVP'), ('supervisor', 'Supervisor'), ('salesperson', 'Corporate Account Manager'), ('vp', 'Vice President'), ('gm', 'General Manager'), ('president', 'President'), ('asm', 'Sales Manager'), ('sm', 'Sales Manager'), ('teamlead', 'Teamlead'), ('techmgr', 'Technical Manager'), ('asst_techmgr', 'Assistant Technical Manager'), ('marketing', 'Marketing')], default='salesperson', max_length=20),
        ),
    ]
