# Generated by Django 5.2.5 on 2026-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username or email that was attempted', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('invalid_credentials', 'Invalid Credentials'), ('account_disabled', 'Account Disabled'), ('mfa_failed', 'MFA Verification Failed'), ('account_locked', 'Account Locked')], default='invalid_credentials', max_length=50)),
            ],
            options={
                'verbose_name': 'Failed Login Attempt',
                'verbose_name_plural': 'Failed Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='users_faile_usernam_88f64e_idx'), models.Index(fields=['ip_address', '-timestamp'], name='users_faile_ip_addr_23b1fc_idx'), models.Index(fields=['-timestamp'], name='users_faile_timesta_dbf89e_idx')],
            },
        ),
    ]
