# Generated by Django 5.2.5 on 2026-09-15 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('self_request', 'Self-service reset requested'), ('self_completed', 'Self-service reset completed'), ('admin_send_link', 'Admin sent reset link'), ('admin_reset_mfa', 'Admin reset MFA')], max_length=32)),
                ('target_identifier', models.CharField(blank=True, help_text='Email/username entered (kept even if no account matched, for abuse detection).', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='Admin who performed an admin-initiated action (null for self-service).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='The account the reset/MFA action applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Audit',
                'verbose_name_plural': 'Password Reset Audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='users_passw_action_5c11ed_idx'), models.Index(fields=['ip_address', '-timestamp'], name='users_passw_ip_addr_f96980_idx'), models.Index(fields=['-timestamp'], name='users_passw_timesta_53f134_idx')],
            },
        ),
    ]
