# Generated by Django 5.2.5 on 2025-08-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customerhistory'),
        ('teams', '0005_alter_group_options_group_group_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-circle', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_customer', models.BooleanField(default=True, help_text='Whether this activity type requires a customer association')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes and outcomes from the activity')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by_supervisor', models.BooleanField(default=False)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales_monitoring.activitytype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
                ('salesperson', models.ForeignKey(limit_choices_to={'role': 'salesperson'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Activity',
                'verbose_name_plural': 'Sales Activities',
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_title', models.CharField(max_length=200)),
                ('proposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('proposal_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating')], default='draft', max_length=20)),
                ('expected_decision_date', models.DateField(blank=True, null=True)),
                ('win_probability', models.PositiveIntegerField(default=50, help_text='Probability of winning (0-100%)')),
                ('sales_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_details', to='sales_monitoring.salesactivity')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('initial', 'Initial Meeting'), ('demo', 'Product Demo'), ('proposal', 'Proposal Presentation'), ('negotiation', 'Negotiation'), ('closing', 'Closing Meeting'), ('follow_up', 'Follow-up Meeting')], default='initial', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('attendees', models.TextField(blank=True, help_text='List of attendees')),
                ('meeting_outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('needs_follow_up', 'Needs Follow-up'), ('not_interested', 'Not Interested'), ('proposal_requested', 'Proposal Requested'), ('deal_closed', 'Deal Closed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('sales_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to='sales_monitoring.salesactivity')),
            ],
        ),
        migrations.CreateModel(
            name='EmailActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('introduction', 'Introduction'), ('follow_up', 'Follow-up'), ('proposal', 'Proposal'), ('quote', 'Quote'), ('contract', 'Contract'), ('thank_you', 'Thank You'), ('newsletter', 'Newsletter')], default='introduction', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('recipients', models.TextField(help_text='Email addresses of recipients')),
                ('has_attachments', models.BooleanField(default=False)),
                ('email_opened', models.BooleanField(default=False, help_text='Whether recipient opened the email')),
                ('email_responded', models.BooleanField(default=False, help_text='Whether recipient responded')),
                ('sales_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_details', to='sales_monitoring.salesactivity')),
            ],
        ),
        migrations.CreateModel(
            name='CallActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('cold', 'Cold Call'), ('warm', 'Warm Call'), ('follow_up', 'Follow-up Call'), ('demo', 'Product Demo'), ('support', 'Customer Support')], default='cold', max_length=20)),
                ('call_outcome', models.CharField(blank=True, choices=[('answered', 'Call Answered'), ('voicemail', 'Left Voicemail'), ('busy', 'Busy/No Answer'), ('wrong_number', 'Wrong Number'), ('not_interested', 'Not Interested'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_requested', 'Proposal Requested')], max_length=30)),
                ('sales_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to='sales_monitoring.salesactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Upcoming Activity'), ('overdue', 'Overdue Activity'), ('follow_up', 'Follow-up Required'), ('review_needed', 'Supervisor Review Needed')], max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reminders', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sales_monitoring.salesactivity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Activity Created'), ('updated', 'Activity Updated'), ('status_changed', 'Status Changed'), ('reviewed', 'Reviewed by Supervisor'), ('completed', 'Activity Completed'), ('cancelled', 'Activity Cancelled')], max_length=20)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales_monitoring.salesactivity')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Period Report')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('completed_activities', models.PositiveIntegerField(default=0)),
                ('calls_made', models.PositiveIntegerField(default=0)),
                ('meetings_held', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('proposals_sent', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('average_activity_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('team_productivity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teams.group')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role__in': ['supervisor', 'asm']}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(choices=[('research', 'Customer Research'), ('preparation', 'Meeting Preparation'), ('documentation', 'Documentation'), ('follow_up', 'Follow-up Action'), ('administrative', 'Administrative'), ('training', 'Training/Learning')], default='administrative', max_length=30)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sales_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_details', to='sales_monitoring.salesactivity')),
            ],
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['salesperson', '-scheduled_start'], name='sales_monit_salespe_1ba6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['customer', '-scheduled_start'], name='sales_monit_custome_71009f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['status', '-scheduled_start'], name='sales_monit_status_50be10_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['activity_type', '-scheduled_start'], name='sales_monit_activit_4d69ba_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['reviewed_by_supervisor'], name='sales_monit_reviewe_e4d5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityreminder',
            index=models.Index(fields=['recipient', 'is_read'], name='sales_monit_recipie_09835e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityreminder',
            index=models.Index(fields=['reminder_type', 'is_sent'], name='sales_monit_reminde_569bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity', '-timestamp'], name='sales_monit_activit_64337f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['changed_by', '-timestamp'], name='sales_monit_changed_a6e2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorreport',
            index=models.Index(fields=['supervisor', '-created_at'], name='sales_monit_supervi_15cfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorreport',
            index=models.Index(fields=['group', '-created_at'], name='sales_monit_group_i_23b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorreport',
            index=models.Index(fields=['period_start', 'period_end'], name='sales_monit_period__7cb011_idx'),
        ),
    ]
