# Generated by Django 6.0.1 on 2026-03-14 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_rename_contact_person_name_delinquentcustomer_assigned_ae'),
        ('sales_funnel', '0005_salesfunnel_proposal'),
        ('sales_monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('success_criteria', models.TextField(help_text='What defines a successful POC?')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed_success', 'Completed - Successful'), ('completed_fail', 'Completed - Failed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='customers.customer')),
                ('lead_engineer', models.ForeignKey(limit_choices_to={'role__in': ['engineer', 'presales', 'salesperson']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_pocs', to=settings.AUTH_USER_MODEL)),
                ('sales_funnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocs', to='sales_funnel.salesfunnel')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pocs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
