MOTIVATIONAL_QUOTES = [
    "“Focus on high-volume activity to compensate for a lack of experience, as anyone can succeed by talking to many people daily.” - Jim Rohn",
    "“While making a sale provides a living, focusing on developing skills is what creates lasting wealth.” - Jim Rohn",
    "“Sales is fundamentally about human connection, requiring personal engagement rather than relying on manuals.” - Jim Rohn",
    "“True success involves caring for clients after the sale and maintaining persistence, treating \"no\" as just a temporary obstacle.” - Jim Rohn",
    "“Focus on becoming a better professional rather than wishing for easier circumstances.” - Jim Rohn",
    "“Success is attracted, not just pursued, by focusing on personal development.” - Jim Rohn",
    "“Embrace the light, daily weight of discipline to avoid the heavy burden of regret.” - Jim Rohn",
    "“Take control of your daily schedule to avoid being controlled by it.” - Jim Rohn",
    "“Salespeople should take lessons from their kids. What does the word 'no' mean to a child? Almost nothing!” - Jim Rohn",
    "“Don't wish it were easier; wish you were better. Don’t wish for less problems; wish for more skills. Don’t wish for less challenge; wish for more wisdom.” - Jim Rohn",
    "“If you are not taking care of your customer, your competitor will.” – Bob Hooey",
    "“Chase the vision, not the money; the money will end up following you.” – Tony Hsieh",
    "“Pretend that every single person you meet has a sign around his or her neck that says, ‘Make me feel important.’ Not only will you succeed in sales, you’ll also succeed in life.” – Mary Kay Ash",
    "“Great salespeople are relationship builders who provide value and help their customers win.” - Jeffrey Gitomer",
    "“90 percent of selling is conviction and 10 percent is persuasion.” – Shiv Khera",
    "“You don’t compete on price. You compete on relationships.” – Patricia Fripp",
    "“I like to think of sales as the ability to gracefully persuade, not manipulate, a person or persons into a win-win situation.” – Bo Bennett",
    "“Don’t find customers for your products, find products for your customers.” – Seth Godin",
    "“Companies should be selling ideas more than benefits. Sell Ideas. Not stuff.” – Aaron Ross",
    "“Make a customer, not a sale.” – Katherine Barchetti",
    "“In sales, a referral is the key to the door of resistance.” – Bo Bennett",
    "“Your most unhappy customers are your greatest source of learning.” – Bill Gates",
    "“Whatever the mind of man can conceive and believe, it can achieve.” – Napoleon Hill",
    "“A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.” – Winston Churchill",
    "“Don’t watch the clock; do what it does. Keep going.” – Sam Levenson",
    "“Winning isn’t everything, but wanting to win is.” – Vince Lombardi",
    "“Always do your best. What you plant now, you will harvest later.” – Og Mandino",
    "“The way to get started is to quit talking and begin doing.” – Walt Disney",
    "“The secret of getting ahead is getting started.” – Mark Twain",
    "“A goal is a dream with a deadline.” – Napoleon Hill",
    "“Well done is better than well said.” – Benjamin Franklin",
    "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.” – Vince Lombardi"
]
