# Generated by Django 5.2.5 on 2026-07-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailing', '0006_campaign_interested_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='recipient_mode',
            field=models.CharField(choices=[('crm', 'CRM Customers'), ('manual', 'Manual Entry')], default='crm', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template_type',
            field=models.CharField(choices=[('product_of_week', 'EDM'), ('newsletter_digest', 'Newsletter Digest')], default='html', max_length=30),
        ),
    ]
