# Generated by Django 5.2.5 on 2026-09-09 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailing', '0007_alter_campaign_recipient_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Details of the announcement or event.')),
                ('announcement_type', models.CharField(choices=[('event', 'Upcoming Event'), ('news', 'News / Update'), ('promo', 'Promotion'), ('edm', 'New EDM / Media')], default='news', max_length=20)),
                ('event_date', models.DateTimeField(blank=True, help_text='For events: when it takes place. Leave blank for general announcements.', null=True)),
                ('location', models.CharField(blank=True, help_text='Optional venue/location for events.', max_length=255)),
                ('link_url', models.URLField(blank=True, help_text='Optional link (e.g. registration, article, media).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
