# Generated by Django 5.2.5 on 2025-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate'), ('education', 'Education'), ('hospitality', 'Hospitality & Tourism'), ('construction', 'Construction'), ('automotive', 'Automotive'), ('agriculture', 'Agriculture'), ('energy', 'Energy & Utilities'), ('media', 'Media & Entertainment'), ('consulting', 'Consulting'), ('government', 'Government'), ('nonprofit', 'Non-profit'), ('other', 'Other')], help_text="Customer's industry sector", max_length=50)),
                ('territory', models.CharField(blank=True, choices=[('makati', 'Makati City'), ('ortigas', 'Ortigas'), ('pasig', 'Pasig City'), ('alabang', 'Alabang'), ('bulacan', 'Bulacan'), ('pampanga', 'Pampanga'), ('laguna', 'laguna'), ('batangas', 'Batangas'), ('quezon', 'Quezon')], help_text='Geographic territory/area', max_length=50)),
                ('is_vip', models.BooleanField(default=False, help_text='Mark as VIP or high-value millionaire account for special handling', verbose_name='VIP/Millionaire Account')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this customer account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_data', models.TextField(help_text='JSON data containing the customer state at backup time')),
                ('reason', models.CharField(default='Manual backup', help_text='Reason for creating this backup', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this backup was created')),
            ],
            options={
                'verbose_name': 'Customer Backup',
                'verbose_name_plural': 'Customer Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
