# Generated by Django 5.2.5 on 2025-08-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salesperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerbackup',
            name='changed_by',
            field=models.ForeignKey(help_text='The user who made the change that triggered this backup', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerbackup',
            name='customer',
            field=models.ForeignKey(help_text='The customer this backup belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_vip'], name='customers_c_is_vip_72cf8e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['industry'], name='customers_c_industr_c5ea21_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['territory'], name='customers_c_territo_49694e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbackup',
            index=models.Index(fields=['customer', '-created_at'], name='customers_c_custome_ab8dd7_idx'),
        ),
    ]
