# Generated by Django 5.2.5 on 2025-08-28 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_industry_alter_customer_territory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Customer Created'), ('updated', 'Customer Updated'), ('vip_enabled', 'Became VIP Customer'), ('vip_disabled', 'VIP Status Removed'), ('activated', 'Customer Activated'), ('deactivated', 'Customer Deactivated'), ('salesperson_assigned', 'Salesperson Assigned'), ('salesperson_changed', 'Salesperson Changed'), ('salesperson_removed', 'Salesperson Removed'), ('restored', 'Restored from Backup'), ('imported', 'Imported from CSV'), ('field_updated', 'Field Updated')], help_text='Type of action performed', max_length=25)),
                ('description', models.TextField(help_text='Detailed description of what changed')),
                ('old_value', models.JSONField(blank=True, help_text='Previous value before the change (JSON format)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value after the change (JSON format)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the browser used')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this change occurred')),
                ('changed_by', models.ForeignKey(help_text='The user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_changes_made', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The customer this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customers.customer')),
                ('salesperson_at_time', models.ForeignKey(blank=True, help_text='The salesperson assigned to the customer at the time of this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_history_as_salesperson', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer History',
                'verbose_name_plural': 'Customer Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', '-timestamp'], name='customers_c_custome_114fbb_idx'), models.Index(fields=['action', '-timestamp'], name='customers_c_action_b736bb_idx'), models.Index(fields=['salesperson_at_time', '-timestamp'], name='customers_c_salespe_90cc57_idx'), models.Index(fields=['changed_by', '-timestamp'], name='customers_c_changed_5eb4cf_idx')],
            },
        ),
    ]
