# Generated by Django 5.2.5 on 2025-08-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person_position',
            field=models.CharField(blank=True, help_text="Contact person's job title or position", max_length=100),
        ),
    ]
