# Generated by Django 6.0.1 on 2026-01-19 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_contact_person_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelinquencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('watch', 'Watch List')], default='open', max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delinquencies', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delinquency_records', to='customers.customer')),
                ('salesperson', models.ForeignKey(blank=True, limit_choices_to={'role': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delinquency_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='customers_d_status_552a97_idx'), models.Index(fields=['due_date'], name='customers_d_due_dat_73a530_idx'), models.Index(fields=['salesperson'], name='customers_d_salespe_1d1f36_idx')],
            },
        ),
    ]
