# Generated by Django 6.0.1 on 2026-01-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_delinquencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='delinquencyrecord',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delinquencyrecord',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
