# Generated by Django 6.0.1 on 2026-01-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_delinquencyrecord_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delinquencyrecord',
            name='notes',
        ),
    ]
