# Generated by Django 6.0.1 on 2026-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_delinquencyrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Customer Created'), ('updated', 'Customer Updated'), ('vip_enabled', 'Became VIP Customer'), ('vip_disabled', 'VIP Status Removed'), ('activated', 'Customer Activated'), ('deactivated', 'Customer Deactivated'), ('salesperson_assigned', 'Salesperson Assigned'), ('salesperson_changed', 'Salesperson Changed'), ('salesperson_removed', 'Salesperson Removed'), ('restored', 'Restored from Backup'), ('imported', 'Imported from CSV'), ('field_updated', 'Field Updated'), ('deal_won', 'Deal Marked Won'), ('deal_lost', 'Deal Marked Lost')], help_text='Type of action performed', max_length=25),
        ),
    ]
