# Generated by Django 6.0.1 on 2026-02-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customerhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='delinquencyrecord',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delinquencyrecord',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
