# Generated by Django 6.0.1 on 2026-02-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_delinquentcustomer_alter_delinquencyrecord_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delinquencyrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delinquency_records', to='customers.delinquentcustomer'),
        ),
        migrations.AlterUniqueTogether(
            name='delinquentcustomer',
            unique_together={('company_name', 'email')},
        ),
    ]
