# Generated by Django 6.0.1 on 2026-02-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_delinquencyrecord_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delinquentcustomer',
            old_name='contact_person_name',
            new_name='assigned_ae',
        ),
    ]
