# Generated by Django 5.2.5 on 2026-03-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customercontact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercontact',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
