# Generated by Django 5.2.5 on 2026-04-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_customercreaterequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customercreaterequest',
            new_name='customers_c_status_34cf10_idx',
            old_name='customers_c_status_5f0a41_idx',
        ),
        migrations.RenameIndex(
            model_name='customercreaterequest',
            new_name='customers_c_company_020f26_idx',
            old_name='customers_c_company_72f64e_idx',
        ),
        migrations.AlterField(
            model_name='customercreaterequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
