# Generated by Django 5.2.5 on 2026-04-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_customer_automation_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_is_mill_e587d6_idx',
            old_name='customers_c_is_mill_8be6fd_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_auto_in_ed6b23_idx',
            old_name='customers_c_auto_in_d34b53_idx',
        ),
    ]
