# Generated by Django 5.2.5 on 2026-07-30 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_rename_customers_c_is_mill_8be6fd_idx_customers_c_is_mill_e587d6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='salesperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role__in': ['salesperson', 'supervisor', 'asm', 'sm', 'avp']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
