# Generated by Django 5.2.5 on 2026-08-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture & Agribusiness'), ('automotive', 'Automotive'), ('business', 'BPO'), ('construction', 'Construction & Engineering'), ('defense', 'Defense & Security'), ('digital', 'Digital Services / IT Services'), ('education', 'Education & Training'), ('energy', 'Energy & Power'), ('financial', 'Financial Services & Banking'), ('government', 'Government & Public Sector'), ('healthcare', 'Healthcare & Medical Services'), ('hospitality', 'Hospitality & Tourism'), ('manufacturing', 'Manufacturing'), ('media', 'Media, Entertainment & Publishing'), ('mining', 'Mining & Quarrying'), ('pharmaceuticals', 'Pharmaceuticals & Life Sciences'), ('realestate', 'Real Estate & Property Development'), ('retail', 'Retail & E-commerce'), ('general', 'General Services'), ('technology', 'Technology <Hardware & Software>'), ('telecommunications', 'Telecommunications'), ('transportation', 'Transportation & Logistics'), ('utilities', 'Utilities <Water, Gas, Electricity>'), ('wholesale', 'Wholesale & Distribution'), ('others', 'Others')], help_text="Customer's industry sector", max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='territory',
            field=models.CharField(blank=True, choices=[('caloocan', 'Caloocan'), ('laspinas', 'Las Piñas'), ('makati', 'Makati'), ('malabon', 'Malabon'), ('mandaluyong', 'Mandaluyong'), ('manila', 'Manila'), ('marikina', 'Marikina'), ('muntinlupa', 'Muntinlupa'), ('navotas', 'Navotas'), ('novaliches', 'Novaliches'), ('paranaque', 'Parañaque'), ('pasay', 'Pasay'), ('pasig', 'Pasig'), ('quezoncity', 'Quezon City'), ('sanjuan', 'San Juan'), ('taguig', 'Taguig'), ('valenzuela', 'Valenzuela'), ('laguna', 'Laguna'), ('batangas', 'Batangas'), ('cavite', 'Cavite'), ('isabela', 'Isabela'), ('rizal', 'Rizal'), ('bicol', 'Bicol'), ('nuevaecija', 'Nueva Ecija'), ('tarlac', 'Tarlac'), ('pampanga', 'Pampanga'), ('baguio', 'Baguio'), ('cebu', 'Cebu'), ('calabarzon', 'Calabarzon'), ('outsidencr', 'Outside NCR'), ('overseas', 'Overseas')], help_text='Geographic territory/area', max_length=50),
        ),
    ]
