# Generated by Django 5.2.5 on 2025-08-29 04:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customerhistory'),
        ('sales_funnel', '0002_salesfunnel_deal_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('territory', models.CharField(blank=True, choices=[('caloocan', 'Caloocan'), ('laspinas', 'Las Piñas'), ('makati', 'Makati'), ('malabon', 'Malabon'), ('mandaluyong', 'Mandaluyong'), ('manila', 'Manila (capital city)'), ('marikina', 'Marikina'), ('muntinlupa', 'Muntinlupa'), ('navotas', 'Navotas'), ('paranaque', 'Parañaque'), ('pasay', 'Pasay'), ('pasig', 'Pasig'), ('quezoncity', 'Quezon City'), ('sanjuan', 'San Juan'), ('taguig', 'Taguig'), ('valenzuela', 'Valenzuela'), ('outsidencr', 'Outside NCR')], help_text='Geographic territory/area', max_length=50)),
                ('industry', models.CharField(blank=True, choices=[('agriculture', 'Agriculture & Agribusiness'), ('automotive', 'Automotive'), ('business', 'Business Process Outsourcing (BPO)'), ('construction', 'Construction & Engineering'), ('defense', 'Defense & Security'), ('digital', 'Digital Services / IT Services'), ('education', 'Education & Training'), ('energy', 'Energy & Power'), ('financial', 'Financial Services & Banking'), ('government', 'Government & Public Sector'), ('healthcare', 'Healthcare & Medical Services'), ('hospitality', 'Hospitality & Tourism'), ('manufacturing', 'Manufacturing'), ('media', 'Media, Entertainment & Publishing'), ('mining', 'Mining & Quarrying'), ('pharmaceuticals', 'Pharmaceuticals & Life Sciences'), ('realestate', 'Real Estate & Property Development'), ('retail', 'Retail & E-commerce'), ('general', 'General Services <for consultancy, repair, logistics, etc.>'), ('technology', 'Technology <Hardware & Software>'), ('telecommunications', 'Telecommunications'), ('transportation', 'Transportation & Logistics'), ('utilities', 'Utilities <Water, Gas, Electricity>'), ('wholesale', 'Wholesale & Distribution'), ('others', 'Others <or anything not covered>')], help_text="Lead's industry sector", max_length=50)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('annual_revenue', models.CharField(blank=True, choices=[('under_1m', 'Under $1M'), ('1m_5m', '$1M - $5M'), ('5m_10m', '$5M - $10M'), ('10m_50m', '$10M - $50M'), ('50m_100m', '$50M - $100M'), ('over_100m', 'Over $100M')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('converted', 'Converted to Customer'), ('lost', 'Lost'), ('unqualified', 'Unqualified')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('hot', 'Hot Lead')], default='medium', max_length=10)),
                ('initial_interest', models.TextField(help_text='What initially interested them?')),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements or needs')),
                ('budget_range', models.CharField(blank=True, choices=[('under_10k', 'Under $10,000'), ('10k_50k', '$10,000 - $50,000'), ('50k_100k', '$50,000 - $100,000'), ('100k_500k', '$100,000 - $500,000'), ('500k_1m', '$500,000 - $1,000,000'), ('over_1m', 'Over $1,000,000')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('immediate', 'Immediate (< 1 month)'), ('short_term', 'Short term (1-3 months)'), ('medium_term', 'Medium term (3-6 months)'), ('long_term', 'Long term (6+ months)'), ('no_timeline', 'No specific timeline')], max_length=20)),
                ('lead_score', models.IntegerField(default=0, help_text='Automated lead score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value of the deal when converted', max_digits=12, null=True)),
                ('first_contact_date', models.DateTimeField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('expected_close_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_qualified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, limit_choices_to={'role': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_lead', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNurturingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('converted', 'Converted to Customer'), ('lost', 'Lost'), ('unqualified', 'Unqualified')], help_text='Target leads with this status', max_length=20)),
                ('target_score_min', models.IntegerField(default=0, help_text='Minimum lead score to target')),
                ('target_score_max', models.IntegerField(default=100, help_text='Maximum lead score to target')),
                ('email_template', models.TextField(blank=True)),
                ('follow_up_days', models.IntegerField(default=7, help_text='Days after which to follow up')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_assign_salesperson', models.BooleanField(default=False, help_text='Automatically assign leads to salespeople')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic_score', models.IntegerField(default=0)),
                ('company_score', models.IntegerField(default=0)),
                ('behavioral_score', models.IntegerField(default=0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('fit_score', models.IntegerField(default=0)),
                ('scoring_breakdown', models.JSONField(blank=True, default=dict)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_details', to='lead_generation.lead')),
            ],
            options={
                'verbose_name': 'Lead Scoring Detail',
                'verbose_name_plural': 'Lead Scoring Details',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('cold_calling', 'Cold Calling'), ('email_marketing', 'Email Marketing'), ('advertising', 'Advertising'), ('trade_show', 'Trade Show'), ('webinar', 'Webinar'), ('content_marketing', 'Content Marketing'), ('seo', 'SEO/Organic Search'), ('paid_search', 'Paid Search'), ('partner', 'Partner'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost_per_lead', models.DecimalField(decimal_places=2, default=0, help_text='Average cost to acquire a lead from this source', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_type', 'is_active'], name='lead_genera_source__34c98f_idx')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead_generation.leadsource'),
        ),
        migrations.CreateModel(
            name='ConversionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
                ('days_to_convert', models.IntegerField(help_text='Days from lead creation to conversion')),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='Initial deal value when converted', max_digits=12, null=True)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost to acquire this lead', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('converted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions_made', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_history', to='customers.customer')),
                ('sales_funnel_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_source', to='sales_funnel.salesfunnel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='lead_generation.lead')),
            ],
            options={
                'ordering': ['-conversion_date'],
                'indexes': [models.Index(fields=['conversion_date'], name='lead_genera_convers_61405f_idx'), models.Index(fields=['converted_by', '-conversion_date'], name='lead_genera_convert_33888f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('proposal', 'Proposal Sent'), ('follow_up', 'Follow-up'), ('research', 'Research'), ('note', 'Note Added'), ('status_change', 'Status Changed')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('no_response', 'No Response'), ('interested', 'Showed Interest'), ('not_interested', 'Not Interested'), ('follow_up_needed', 'Follow-up Needed'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_requested', 'Proposal Requested')], max_length=30)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lead_generation.lead')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_genera_lead_id_1a29ca_idx'), models.Index(fields=['activity_type', '-created_at'], name='lead_genera_activit_5990aa_idx'), models.Index(fields=['performed_by', '-created_at'], name='lead_genera_perform_feda03_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_salesperson'], name='lead_genera_status_934048_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_score', '-created_at'], name='lead_genera_lead_sc_8c948f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'status'], name='lead_genera_source__51092e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority', '-created_at'], name='lead_genera_priorit_114bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_date'], name='lead_genera_next_fo_85e9c7_idx'),
        ),
    ]
