# Generated by Django 5.2.5 on 2025-08-29 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerhistory'),
        ('lead_generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_genera_status_934048_idx',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_salesperson',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='activity_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='initial_interest',
            field=models.TextField(blank=True, help_text='What initially interested them?'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='lead_genera_status_bbea94_idx'),
        ),
    ]
