# Generated by Django 5.2.5 on 2025-08-29 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generation', '0002_remove_lead_lead_genera_status_934048_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(blank=True, choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('proposal', 'Proposal Sent'), ('follow_up', 'Follow-up'), ('research', 'Research'), ('note', 'Note Added'), ('status_change', 'Status Changed')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('no_response', 'No Response'), ('interested', 'Showed Interest'), ('not_interested', 'Not Interested'), ('follow_up_needed', 'Follow-up Needed'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_requested', 'Proposal Requested')], max_length=30)),
                ('points_per_activity', models.IntegerField(default=5)),
                ('max_points_per_day', models.IntegerField(default=25)),
                ('decay_days', models.IntegerField(default=30, help_text='Days after which activity points start decaying')),
                ('decay_rate', models.DecimalField(decimal_places=2, default=0.1, help_text='Daily decay rate (0.10 = 10% per day)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activity_type', 'outcome'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_assign_threshold', models.IntegerField(default=80, help_text='Score threshold for automatic assignment to salespeople')),
                ('hot_lead_threshold', models.IntegerField(default=75, help_text="Score threshold to mark leads as 'hot'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria_type', models.CharField(choices=[('demographic', 'Demographic'), ('firmographic', 'Firmographic'), ('behavioral', 'Behavioral'), ('engagement', 'Engagement'), ('source', 'Source Quality'), ('temporal', 'Temporal')], max_length=20)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight multiplier for this criteria (0.1 to 10.0)', max_digits=5)),
                ('max_score', models.IntegerField(default=100, help_text='Maximum points this criteria can contribute', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scoring Criteria',
                'ordering': ['criteria_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Profile-specific weight multiplier', max_digits=5)),
                ('is_enabled', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_generation.leadscoringprofile')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_generation.scoringcriteria')),
            ],
            options={
                'unique_together': {('profile', 'criteria')},
            },
        ),
        migrations.AddField(
            model_name='leadscoringprofile',
            name='criteria',
            field=models.ManyToManyField(through='lead_generation.ProfileCriteria', to='lead_generation.scoringcriteria'),
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Lead model field name (e.g., 'company_size', 'annual_revenue')", max_length=100)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('contains', 'Contains'), ('in', 'In list'), ('not_in', 'Not in list'), ('is_null', 'Is empty/null'), ('is_not_null', 'Is not empty/null'), ('regex', 'Matches pattern')], max_length=20)),
                ('value', models.TextField(help_text='Value to compare against (JSON for complex values)')),
                ('points', models.IntegerField(help_text='Points awarded when this rule matches (-100 to 100)', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Evaluation order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='lead_generation.scoringcriteria')),
            ],
            options={
                'ordering': ['criteria', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('demographic_score', models.IntegerField(default=0)),
                ('firmographic_score', models.IntegerField(default=0)),
                ('behavioral_score', models.IntegerField(default=0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('source_score', models.IntegerField(default=0)),
                ('temporal_score', models.IntegerField(default=0)),
                ('calculation_details', models.JSONField(default=dict)),
                ('score_change', models.IntegerField(default=0)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='lead_generation.lead')),
                ('scoring_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_generation.leadscoringprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_genera_lead_id_b146bd_idx'), models.Index(fields=['total_score'], name='lead_genera_total_s_1da47b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('hot_lead', 'Hot Lead Alert'), ('score_increase', 'Score Increase Alert'), ('score_decrease', 'Score Decrease Alert'), ('threshold_reached', 'Threshold Reached'), ('assignment_needed', 'Assignment Needed')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('threshold_value', models.IntegerField(blank=True, null=True)),
                ('current_score', models.IntegerField()),
                ('notify_supervisors', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_alerts', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_alerts', to='lead_generation.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'is_read'], name='lead_genera_assigne_114ab6_idx'), models.Index(fields=['alert_type', 'priority'], name='lead_genera_alert_t_c1def5_idx')],
            },
        ),
    ]
