# Generated by Django 5.2.5 on 2025-08-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generation', '0003_activityscoringrule_leadscoringprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='annual_revenue',
            field=models.CharField(blank=True, choices=[('under_1m', 'Under ₱1M'), ('1m_5m', '₱1M - ₱5M'), ('5m_10m', '₱5M - ₱10M'), ('10m_50m', '₱10M - ₱50M'), ('50m_100m', '₱50M - ₱100M'), ('over_100m', 'Over ₱100M')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_10k', 'Under ₱10,000'), ('10k_50k', '₱10,000 - ₱50,000'), ('50k_100k', '₱50,000 - ₱100,000'), ('100k_500k', '₱100,000 - ₱500,000'), ('500k_1m', '₱500,000 - ₱1,000,000'), ('over_1m', 'Over ₱1,000,000')], max_length=20),
        ),
    ]
