# Generated by Django 5.2.5 on 2026-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generation', '0005_add_created_by_to_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='source_type',
            field=models.CharField(choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('cold_calling', 'Cold Calling'), ('email_marketing', 'Email Marketing'), ('advertising', 'Advertising'), ('trade_show', 'Events'), ('webinar', 'Webinar'), ('content_marketing', 'Content Marketing'), ('seo', 'SEO/Organic Search'), ('paid_search', 'Paid Search'), ('partner', 'Partner'), ('other', 'Other')], max_length=20),
        ),
    ]
