# Generated by Django 5.2.5 on 2026-08-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generation', '0006_alter_leadsource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture & Agribusiness'), ('automotive', 'Automotive'), ('business', 'Business Process Outsourcing (BPO)'), ('construction', 'Construction & Engineering'), ('defense', 'Defense & Security'), ('digital', 'Digital Services / IT Services'), ('education', 'Education & Training'), ('energy', 'Energy & Power'), ('financial', 'Financial Services & Banking'), ('government', 'Government & Public Sector'), ('healthcare', 'Healthcare & Medical Services'), ('hospitality', 'Hospitality & Tourism'), ('manufacturing', 'Manufacturing'), ('media', 'Media, Entertainment & Publishing'), ('mining', 'Mining & Quarrying'), ('pharmaceuticals', 'Pharmaceuticals & Life Sciences'), ('realestate', 'Real Estate & Property Development'), ('retail', 'Retail & E-commerce'), ('general', 'General Services'), ('technology', 'Technology <Hardware & Software>'), ('telecommunications', 'Telecommunications'), ('transportation', 'Transportation & Logistics'), ('utilities', 'Utilities <Water, Gas, Electricity>'), ('wholesale', 'Wholesale & Distribution'), ('others', 'Others <or anything not covered>')], help_text="Lead's industry sector", max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='territory',
            field=models.CharField(blank=True, choices=[('caloocan', 'Caloocan'), ('laspinas', 'Las Piñas'), ('makati', 'Makati'), ('malabon', 'Malabon'), ('mandaluyong', 'Mandaluyong'), ('manila', 'Manila'), ('marikina', 'Marikina'), ('muntinlupa', 'Muntinlupa'), ('navotas', 'Navotas'), ('paranaque', 'Parañaque'), ('pasay', 'Pasay'), ('pasig', 'Pasig'), ('quezoncity', 'Quezon City'), ('sanjuan', 'San Juan'), ('taguig', 'Taguig'), ('valenzuela', 'Valenzuela'), ('laguna', 'Laguna'), ('batangas', 'Batangas'), ('cavite', 'Cavite'), ('isabela', 'Isabela'), ('rizal', 'Rizal'), ('bicol', 'Bicol'), ('nuevaecija', 'Nueva Ecija'), ('baguio', 'Baguio'), ('calabarzon', 'Calabarzon'), ('outsidencr', 'Outside NCR')], help_text='Geographic territory/area', max_length=50),
        ),
    ]
