# Generated by Django 6.0.1 on 2026-03-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional manual reference number (e.g., Ref No: MVD03022026 155)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='availability',
            field=models.CharField(blank=True, help_text='Product availability (e.g. In Stock, 2-3 weeks)', max_length=100),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='part_number',
            field=models.CharField(blank=True, help_text='Product Part Number', max_length=100),
        ),
    ]
