# Generated by Django 6.0.1 on 2026-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0002_proposal_reference_number_proposalitem_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='delivery_lead_time',
            field=models.CharField(default='Within five (5) to ten (10) working days from receipt of confirmed purchased order.', help_text='e.g., 5-10 working days', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='payment_terms',
            field=models.CharField(default='30 days', help_text='e.g., 30 days, Cash on Delivery', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='warranty',
            field=models.CharField(default='1 year - Parts Warranty', help_text='e.g., 1 year - Parts Warranty', max_length=200),
        ),
    ]
