# Generated by Django 6.0.1 on 2026-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0003_proposal_delivery_lead_time_proposal_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Amount - Total Cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of all items', max_digits=12),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit (Internal)', max_digits=12),
        ),
    ]
