# Generated by Django 6.0.1 on 2026-03-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0004_proposal_gross_profit_proposal_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalitem',
            name='description',
            field=models.TextField(help_text='Item description and specifications'),
        ),
    ]
