# Generated by Django 6.0.1 on 2026-03-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0005_alter_proposalitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='currency',
            field=models.CharField(choices=[('PHP', 'PHP - Philippine Peso'), ('USD', 'USD - US Dollar')], default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='proposal',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Exchange rate to PHP (1.0 for PHP)', max_digits=10),
        ),
    ]
