# Generated by Django 6.0.1 on 2026-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0006_proposal_currency_proposal_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tax_type',
            field=models.CharField(choices=[('VAT', 'VAT (12%)'), ('ZERO', 'Zero-Rated (0%)'), ('EXEMPT', 'VAT-Exempt (0%)')], default='VAT', max_length=10),
        ),
    ]
