# Generated by Django 6.0.1 on 2026-03-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0007_proposal_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='cancellation_terms',
            field=models.CharField(choices=[('professional', 'Professional and Direct'), ('process', 'Process-Oriented'), ('polite', 'Short and Polite'), ('partnership', 'Partnership-focused')], default='professional', help_text='Select the tone/wording for the cancellation policy', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='special_note',
            field=models.TextField(blank=True, help_text='Optional special note (e.g. SUBJECT PRICE CHANGE...)'),
        ),
    ]
