# Generated by Django 6.0.1 on 2026-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0008_proposal_cancellation_terms_proposal_special_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='include_bank_details',
            field=models.BooleanField(default=False, help_text='Include bank details in the proposal PDF'),
        ),
    ]
