# Generated by Django 5.2.5 on 2026-03-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0009_proposal_include_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional manual reference number (e.g., Ref No: GGV03022026155)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Internal', max_digits=12),
        ),
    ]
