# Generated by Django 5.2.5 on 2026-03-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0010_alter_proposal_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proposal',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='proposal',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
