# Generated by Django 5.2.5 on 2026-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0018_bank_details_per_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalchangelog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='cancellation_terms',
            field=models.CharField(choices=[('polite', 'Short and Polite')], default='professional', help_text='Select the tone/wording for the cancellation policy', max_length=20),
        ),
    ]
