# Generated by Django 5.2.5 on 2026-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0025_proposalitem_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='usd_beneficiary_name',
            field=models.CharField(default='MICRO IMAGE INTERNATIONAL CORP.', max_length=200),
        ),
    ]
