# Generated by Django 5.2.5 on 2026-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0028_alter_proposal_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='delivery_lead_time',
            field=models.CharField(default='Within three (3) to seven (7) working days once the stock arrived.', help_text='e.g., 3-7 working days once the stock arrived', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional manual reference number (e.g., Ref No: GGV20260523001)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='stock_availability',
            field=models.CharField(blank=True, choices=[('', '---------'), ('ON-STOCK 3 TO 5 WORKING DAYS', 'ON-STOCK 3 TO 5 WORKING DAYS'), ('LIMITED STOCK', 'LIMITED STOCK'), ('ORDER BASIS', 'ORDER BASIS'), ('ORDER BASIS (30 TO 45 WORKING DAYS)', 'ORDER BASIS (30 TO 45 WORKING DAYS)'), ('ORDER BASIS (60 TO 90 WORKING DAYS)', 'ORDER BASIS (60 TO 90 WORKING DAYS)'), ('ORDER BASIS (90 TO 120 WORKING DAYS)', 'ORDER BASIS (90 TO 120 WORKING DAYS)'), ('ORDER BASIS (7 TO 10 WORKING DAYS)', 'ORDER BASIS (7 TO 10 WORKING DAYS)'), ('CONFIG TO ORDER (30 TO 45 WORKING DAYS)', 'CONFIG TO ORDER (30 TO 45 WORKING DAYS)'), ('CONFIG TO ORDER (60 TO 90 WORKING DAYS)', 'CONFIG TO ORDER (60 TO 90 WORKING DAYS)'), ('CONFIG TO ORDER (90 TO 120 WORKING DAYS)', 'CONFIG TO ORDER (90 TO 120 WORKING DAYS)')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='bundled_items',
            field=models.TextField(blank=True, help_text='One bundled component per line. Format: PART NUMBER | Description | Qty'),
        ),
    ]
