# Generated by Django 5.2.5 on 2026-07-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0029_alter_proposal_delivery_lead_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='cancellation_terms',
            field=models.CharField(default='polite', editable=False, max_length=20),
        ),
    ]
