# Generated by Django 5.2.5 on 2026-08-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0030_fix_cancellation_terms_hardcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='use_total_price_label',
            field=models.BooleanField(default=False, help_text="Use 'Total Price' instead of 'Extended Price' as column header in PDF and detail view"),
        ),
    ]
