# Generated by Django 5.2.5 on 2026-08-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0031_add_use_total_price_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_multi_option',
            field=models.BooleanField(default=False, help_text='Enable multi-option format (OPTION 1, OPTION 2, etc.) with separate item tables per option'),
        ),
        migrations.CreateModel(
            name='ProposalOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OPTION 1', help_text='Display name for this option group', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this option group')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='sales_proposals.proposal')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='option_group',
            field=models.ForeignKey(blank=True, help_text='Only set for multi-option proposals', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='sales_proposals.proposaloptiongroup'),
        ),
    ]
