# Generated by Django 5.2.5 on 2026-09-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0036_proposal_bank_details_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalitem',
            name='availability',
            field=models.CharField(blank=True, help_text='Product availability (e.g. In Stock, 2-3 weeks)', max_length=150),
        ),
    ]
