# Generated by Django 5.2.5 on 2026-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0037_alter_proposalitem_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hide_part_number',
            field=models.BooleanField(default=False, help_text="Hide the 'Part No.' column in the proposal PDF and detail view; the freed space is given to the Description column. Use for proposals that don't quote part numbers."),
        ),
    ]
