# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(help_text='Date when this funnel entry was created')),
                ('company_name', models.CharField(help_text='Name of the company for this proposal', max_length=200)),
                ('requirement_description', models.TextField(help_text="Description of the customer's requirements")),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost/expense for this proposal', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('retail', models.DecimalField(decimal_places=2, help_text='Retail price quoted to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stage', models.CharField(choices=[('quoted', 'Newly Quoted'), ('closable', 'Closable This Month'), ('project', 'Project Based')], default='quoted', help_text='Current stage of this proposal in the sales funnel', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, help_text='Expected date to close this deal', null=True)),
                ('probability', models.IntegerField(default=50, help_text='Probability of closing this deal (0-100%)', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this proposal')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this funnel entry is active')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether this deal has been closed (won or lost)')),
                ('closed_date', models.DateField(blank=True, help_text='Date when this deal was closed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Associated customer (if exists in customer database)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_entries', to='customers.customer')),
                ('salesperson', models.ForeignKey(help_text='Salesperson responsible for this proposal', limit_choices_to={'role': 'salesperson'}, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Funnel Entry',
                'verbose_name_plural': 'Sales Funnel Entries',
                'ordering': ['-date_created', '-created_at'],
                'indexes': [models.Index(fields=['salesperson', 'stage'], name='sales_funne_salespe_bdad49_idx'), models.Index(fields=['stage', 'is_active'], name='sales_funne_stage_a1836b_idx'), models.Index(fields=['date_created'], name='sales_funne_date_cr_c274e9_idx'), models.Index(fields=['expected_close_date'], name='sales_funne_expecte_381b54_idx')],
            },
        ),
    ]
