# Generated by Django 5.2.5 on 2025-08-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfunnel',
            name='deal_outcome',
            field=models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost')], default='active', help_text='Outcome of this deal - active, won, or lost', max_length=20),
        ),
    ]
