# Generated by Django 6.0.1 on 2026-01-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0002_salesfunnel_deal_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfunnel',
            name='stage',
            field=models.CharField(choices=[('quoted', 'Newly Quoted'), ('closable', 'Closable This Month'), ('project', 'Project Based'), ('services', 'Services')], default='quoted', help_text='Current stage of this proposal in the sales funnel', max_length=20),
        ),
    ]
