# Generated by Django 6.0.1 on 2026-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0003_alter_salesfunnel_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfunnel',
            name='stage',
            field=models.CharField(choices=[('quoted', 'Newly Quoted'), ('closable', 'Closable Deals'), ('project', 'Green Funnel'), ('services', 'Blue Funnel')], default='quoted', help_text='Current stage of this proposal in the sales funnel', max_length=20),
        ),
    ]
