# Generated by Django 6.0.1 on 2026-03-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0004_alter_salesfunnel_stage'),
        ('sales_proposals', '0004_proposal_gross_profit_proposal_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfunnel',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='The proposal that generated this funnel entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_entries', to='sales_proposals.proposal'),
        ),
    ]
