# Generated by Django 5.2.5 on 2026-05-19 09:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0006_salesfunnel_brand'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesfunnel',
            new_name='sales_funne_brand_e18e38_idx',
            old_name='sales_funnel_brand_idx',
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='retail',
            field=models.DecimalField(decimal_places=2, help_text='SRP quoted to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
