# Generated by Django 5.2.5 on 2026-07-23 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0007_rename_sales_funnel_brand_idx_sales_funne_brand_e18e38_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfunnel',
            name='salesperson',
            field=models.ForeignKey(help_text='Account Manager responsible for this proposal', limit_choices_to={'role': 'salesperson'}, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
